# Generated by Django 4.2.30 on 2026-04-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Balloon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "balloon_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Balloon ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRE_FLIGHT", "Pre-Flight"),
                            ("IN_FLIGHT", "In-Flight"),
                            ("RECOVERY", "Recovery"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="PRE_FLIGHT",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelemetryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField(help_text="Altitude in meters")),
                ("temperature", models.FloatField(help_text="Temperature in Celsius")),
                (
                    "battery_level",
                    models.FloatField(
                        help_text="Battery level as a percentage (0-100)"
                    ),
                ),
                (
                    "balloon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_data",
                        to="telemetry.balloon",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Telemetry Data",
                "ordering": ["-timestamp"],
            },
        ),
    ]
