# Generated by Django 4.2.30 on 2026-04-24 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0002_balloonimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telemetrydata",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="balloon",
            name="balloon_id",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="balloon",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("lost", "Lost"), ("landed", "Landed")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="balloonimage",
            name="image_url",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="altitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="balloon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telemetry",
                to="telemetry.balloon",
            ),
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="battery_level",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="temperature",
            field=models.FloatField(),
        ),
    ]
