# Generated by Django 5.2.13 on 2026-05-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0004_create_default_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="telemetrydata",
            name="flight_phase",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
