# Generated by Django 5.2.13 on 2026-05-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0005_telemetrydata_flight_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="balloonimage",
            name="filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
