# Generated by Django 5.2.13 on 2026-05-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0006_balloonimage_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="balloonimage",
            name="rotation",
            field=models.IntegerField(
                choices=[(0, "0°"), (90, "90°"), (180, "180°"), (270, "270°")],
                default=0,
            ),
        ),
    ]
