# Generated by Django 5.2.13 on 2026-05-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0007_balloonimage_rotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balloon",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("lost", "Lost"),
                    ("landed", "Landed"),
                    ("deactivated", "Deactivated"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
